# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main",  "protocol-registry-v2" ]

jobs:
  ubuntu:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      TEST_INTEGRATION: "TRUE"
      DISPLAY: ":99"
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: mkdir -p ~/.local/share/applications
    - run: sudo apt-get update
    - run: sudo apt-get install -y xvfb xdg-utils libgtk-3-0
    - run: Xvfb :99 -screen 0 1024x768x24
    - run: sudo apt-get install -y libgtk-3-dev libglib2.0-dev
    - run: sudo apt install gnome-shell
    - run: export XDG_DATA_DIRS="$HOME/.local/share:$XDG_DATA_DIRS"
    - run: npm i
    - run: npm run build --if-present
    - run: export XDG_DATA_DIRS="$HOME/.local/share:/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop" ; npm run check
    
  windows:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      TEST_INTEGRATION: "TRUE"
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
    - run: npm run check
  macos:

    runs-on:	macos-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      TEST_INTEGRATION: "TRUE"
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
    - run: npm run check
